name: Syntax Validator
on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Markdown Linting
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: '_posts/*.markdown'
