name: Syntax Validator
on: [ push, pull_request]

permissions:
  contents: write

jobs:
  linting:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Changed files
        uses: tj-actions/changed-files@v45
        id: changed-files
        with:
          files: '_posts/*.{md,markdown}'
          separator: ","
      - name: Markdown Linting
        uses: DavidAnson/markdownlint-cli2-action@v18
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          globs: ${{ steps.changed-files.outputs.all_changed_files }}
          separator: ","
          fix: true